services:
  - type: web
    name: sigrh-backend
    runtime: docker
    plan: free
    rootDir: sigrh-backend
    dockerfilePath: ./Dockerfile
    dockerContext: ./
    autoDeployTrigger: commit
    healthCheckPath: /api-docs
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: CORS_ORIGINS
        value: https://sigrh-frontend-1hhsjca8l-johntarick51-9571.vercel.app,http://localhost:5173
      - key: JAVA_VERSION
        value: "21"